[package]
name = "rust-interface-tests-helper"
version = "0.1.0"
authors = ["vagrant"]
repository = "https://github.com/jean553/rust-interface-tests-helper"

[dependencies]
reqwest = "*"

[dev-dependencies]
mockito = "*"

[lib]
name = "rust_interface_tests_helper"
path = "src/lib.rs"
